==  Modern Web Application Development for Java Programmers

Java ecosystem offers lots of different ways to architect, develop, and deploy a distributed Web application. The parallel ecosystem known as HTML5 offers lots of different ways to design, develop, and deploy the cross-platform UI that works on multiple Web browsers and variety of devices. 

This online training class will give you a practical knowledge of developing front and back end components by  immersing into an environment similar to a real-world enterprise setup. Be prepared to download, install and master lots of various software packages that will be used at different stages of training.

We'll spend about 40% of the time developing User Interface in HTML5 and about 60% working on the server-side Java code. During the first three sessions we'll be working only with HTML and related JavaScript libraries. The server side Java programming starts on session 4, when the UI is ready.  

=== Course Outline 

* *Unit 1.* Creating a wireframe of the UI of the online auction. Developing and Debugging in HTML/JavaScript. Fast pace introduction to JavaScript. Intro to GIT/Github. Think mobile:  Intro to Responsive Web Design. Mocking up the UI. Creating the first prototype of the auction in pure HTML/JavaScript/CSS. Configuring the auction project in IntelliJ IDEA. Here's link:timeline.adoc#unit-1[the timeline] for this lesson.

* *Unit 2.*  Becoming productive with JavaScript: Intro TypeScript. Overview of JavaScript cross-browser frameworks. Creating the Web project with  AngularJS framework. Configuring libraries in IntelliJ IDEA. Styling with Bootstrap.  Mocking up server side with Angular. Developing first two pages of the auction app.Hello World in Grunt. Here's link:timeline.adoc#unit-2[the timeline] for this lesson.

* *Unit 3.* AngularJS framework in depth.  Creating the second prototype of the UI. Build automation with Grunt. Package Management with Bower.

_One week break for self study and catching up._

* *Unit 4.* Introducing Test-Driven Development in JavaScript. Test-driven is not test-first. Creating test scripts for models, views, controllers with Jasmine.js. AJAX. JSON. REST, HATEOAS. Creating the third prototype of the UI (consuming JSON from the server via HTTP protocol).

* *Unit 5.* Java SE 8: major upgrade. Java EE 7: boost in developers' productivity. Configuring Java EE application server. Creating the Java EE version of the server-side app. Integration with UI.

* *Unit 6.* Intro to WebSockets. Creating the forth prototype of the UI (Server pushes data to the client via WebSocket).

_One week break for self study and catching up._

* *Unit 7.* Test-Driven Development in Java. JUnit and Spock. Creating data storage for online auction. Configuring Oracle DBMS server. JDBC vs JPA. SQL mapping framework MyBatis. Build scripts with Gradle. Database versioning and migration (Dev -> QA -> Prod).

* *Unit 8.* Intro to Java Messaging. Configuring Messaging Server (mocking a bidding engine). Testing communication between the Java EE application and messaging servers. Load testing with JMeter.

* *Unit 9.* Spring Framework 4 (core, security, MVC, JdbcTemplate). Creating the Spring version of the server-side app. Integration with the auction UI.

* *Unit 10.* Code review and discussing the final version of the online auction Web application.


=== Prerequisites 

Attendees should plan on committing about 15-20 hours a week for studying and working on the assignments from this course. We'll split the class into small teams to work on the assignments during the week, so your contribution is required. 

Attendees must know basic HTML tags (see http://docs.webplatform.org/wiki/html/tutorials ).

While we'll spend 15 min in Unit1 covering Git basics, we recommend you to watch http://flexblog.faratasystems.com/2013/11/08/intro-to-working-with-git-and-github[this video] before this training starts.

Attendees must have a working knowledge of core Java, and understanding of Java EE technologies.


Each attendee has to have a modern computer with plenty of disk space (4+ GB of RAM is recommended).

Having a decent Internet connection (more than 2Mbps) is a must.


=== How

This class will be a  a mix of theory (40%) and practical work (60%). During this training attendees will develop an online auction. This auction should look good and be functional on desktops, tablets and smartphones.

This training will consist of 10 weekly 3-hour online live sessions on the weekend (see the registration page for your group for detail) and 9 optional one-hour meetings in between.  We'll use screen-sharing software. Attendees will be able to hear and see the instructors and will communicate with them via a chat room. 

=== When's the Next Training

The registration page of the upcoming class is http://www.eventbrite.com/e/modern-web-application-development-for-java-programmers-march-2014-tickets-10538467841[here]. 


=== Tools and Technologies

Here's the current list of the software that we'll use in this course.

==== Front end

* HTML
* CSS
* Responsive Web Design principles
* JavaScript
* http://www.typescriptlang.org/[TypeScript]
* JSON
* http://angularjs.org/[AngularJS framework]
* http://getbootstrap.com/[Twitter Bootstrap framework]
* Google Chrome Web Browser
* WebSockets https://developer.mozilla.org/en-US/docs/WebSockets[on the client] 
* http://gruntjs.com/[Grunt] (The JavaScript task runner)
* https://npmjs.org/[NPM]
* http://bower.io/[Bower]
* https://github.com/pivotal/jasmine[Jasmine framework]

==== Middle Tier

* http://www.oracle.com/technetwork/java/javase/overview/index.html/[Java SE 8]
* http://www.oracle.com/technetwork/java/javaee/overview/index.html[Java EE 7]
* SQL: JDBC or http://mybatis.github.io/mybatis-3/[MyBatis]
* https://spring.io/blog/2013/11/01/spring-framework-4-0-rc1-available[Spring 4 Framework] (some modules)
* http://www.wildfly.org/[JBoss Wildfly] Application Server
* WebSockets https://jcp.org/en/jsr/detail?id=356[on the server (JSR-356])
* http://www.jboss.org/hornetq[JBoss HornetQ](Java Messaging)
* http://docs.oracle.com/javaee/7/tutorial/doc/jaxrs-advanced.htm#GJJXE[JAX-RS] (Java API for RESTful Web services)
* http://www.gradle.org/[Gradle]  (build automation)
* https://code.google.com/p/spock/[Spock] or JUnit (unit testing and mocking)
* Load testing with http://jmeter.apache.org/[jMeter].

==== DBMS 

* Oracle  

==== Miscellaneous

* JetBrains TeamCity (continuous integration, code coverage)
* Git (version control system), GitHub (Git hosting service)
* IntelliJ IDEA IDE Ultimate. Our special thanks to JetBrains for providing free classroom license for all the students enrolled into this class.

=== Instructors

Three instructors will teach this course. All of them are practitioners employed by http://faratasystems.com/[Farata Systems]:

* *Yakov Fain (USA)* - Co-founder of Farata Systems, the IT consultancy. https://java.net/website/java-champions/bios.html[Java Champion]. Organizer of the http://www.meetup.com/NJFlex/[Princeton Java Users Group]. Authored and co-authored a number of technical books on programming. Yakov presented on various international conferences on Java and JavaScript related topics.

* *Viktor Gamov (USA)* - Lead software developer in Farata Systems. Helps financial companies with various Java and HTML5 projects. Co-organizer of the Princeton Java Users Group. Co-author of the O'Reilly book on http://enterprisewebbook.com/[Enterprise Web Development]. Viktor presented on various international conferences on Java and JavaScript related topics.

* *Anton Moiseev (Russia)* - Lead software developer in Farata Systems. Specializes in developing e-Commerce applications. Enjoys everything HTML5-related. Authored and taught trainings on developing Web applications with Ext JS framework.

Other professionals from Farata Systems may also be invited to share their experience in developing and deploying complex enterprise systems. 

