= Modern Web Application Development for Java Programmers
© 2014 Farata Systems LLC.
2014-03-11
:revdate: 2014-03-11 12:00:32 -0600
:linkattrs:
:ast: &ast;
:y: &#10003;
:n: &#10008;
:y: icon:check-sign[role="green"]
:n: icon:check-minus[role="red"]
:c: icon:file-text-alt[role="blue"]
:toc:
:toc-placement!:
:toc-title: Table of Contents
:toclevels: 3
:idprefix:
:idseparator: -
:sectanchors:
:icons: font
:source-highlighter: highlight.js
:highlightjs-theme: idea
:experimental:

Java ecosystem offers lots of different ways to architect, develop, and deploy a distributed Web application. The parallel ecosystem known as HTML5 offers lots of different ways to design, develop, and deploy the cross-platform UI that works on multiple Web browsers and variety of devices.

toc::[]

== Enter The Modern Web Application Development

This online training class will give you a practical knowledge of developing front and back end components by  immersing into an environment similar to a real-world enterprise setup. Be prepared to download, install and master lots of various software packages that will be used at different stages of training.

We'll spend about 40% of the time developing User Interface in HTML5 and about 60% working on the server-side Java code. During the first half of the course sessions we'll be working only with HTML, JavaScript and related libraries and frameworks. The Java-related topics are covered in the second part of this training.

=== Course Outline

* *Unit 1.* Creating a wireframe of the UI of the online auction. Developing and Debugging in HTML/JavaScript. Fast pace introduction to JavaScript. Intro to GIT/Github. Think mobile:  Intro to Responsive Web Design. Mocking up the UI. Creating the first prototype of the auction in pure HTML/JavaScript/CSS. Configuring the auction project in IntelliJ IDEA. Styling with Bootstrap. Here's link:timeline.adoc#unit-1[the timeline] of this lesson.

* *Unit 2.*   Intro to Google AngularJS framework. Configuring libraries in IntelliJ IDEA.  Re-creating the first two pages of the auction app. Installing NPM and Grunt.  Configuring Grunt. Here's link:timeline.adoc#unit-2[the timeline] for this lesson.

* *Unit 3.* Creating the second prototype of the UI with AngularJS. Scopes. Adding more tools: package management with Bower. Project scaffolding with Yeoman. Here's link:timeline.adoc#unit-3[the timeline] of this lesson.

* *Unit 4.* AngularJS framework in depth. Forms, REST interaction and custom reusable components. Mocking up server side with AngularJS.

* *Unit 5.* Introducing Test-Driven Development in JavaScript. Test-driven is not test-first. Creating test scripts for models, views, controllers with Jasmine.js. AJAX. JSON. REST, HATEOAS. Creating the third prototype of the UI (consuming JSON from the server via HTTP protocol). Here's link:timeline.adoc#unit-5[the timeline] for this lesson.

_One week break for self study and catching up._

* *Unit 6.* 
+

_Prerequisites_
+

* Download and install http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java SE Development Kit 8] 
+

_Java SE 8_. Overview of the selected new features (lambda-expressions, Streams API, Default Methods in interfaces). Applying bulk operations on the collections of auctions items.  Java build automation with Gradle. Test-Driven Development in Java. JUnit and Spock. Here's link:timeline.adoc#unit-6[the timeline] of this lesson.

* *Unit 7.* 
+

_Prerequisites_
+

* Install WildFly server (_TBD_ link)
* Configure IDE (_TBD_ link to video) 
+

_Java EE 7_. Overview of the new features. Creating the Java EE version of the server-side auction (JAX-RS, CDI). Intro to WebSockets (WebSocket API, JSR-356). Pushing the auction data to the client using WebSocket.

* *Unit 8.*
+

_Prerequisites_

* Install DBMS server
* Configure IDE to connect to the database
+

Creating data storage for online auction. JDBC vs JPA. SQL mapping framework MyBatis. 

* *Unit 9.* Intro to Java Messaging. JMS 2.0. JNDI.  Configuring Messaging Server (mocking a bidding engine). Bringing messaging into the Auction application.


* *Unit 10.* Spring Framework 4 (core, security, MVC, JdbcTemplate). Creating the Spring version of the server-side app. Integration with the auction UI. Code review and discussing the Spring version of the Auction Web application.

=== Prerequisites

Attendees should plan on committing about 15-20 hours a week for studying and working on the assignments from this course. We'll split the class into small teams to work on the assignments during the week, so your contribution is required.

Attendees must know basic HTML tags (see http://docs.webplatform.org/wiki/html/tutorials ).

We'll be using Git version control system during this course. To get familiar with Git and GitHub watch http://flexblog.faratasystems.com/2013/11/08/intro-to-working-with-git-and-github[our training video] before this training starts.

Attendees must have a working knowledge of core Java, and understanding of Java EE technologies.

Each attendee has to have a modern computer with plenty of disk space (4+ GB of RAM is recommended).

Having a decent Internet connection (more than 4Mbps for download) is a must.


=== How

This class will be a  a mix of theory (40%) and practical work (60%). During this training attendees will develop an online auction. This auction should look good and be functional on desktops, tablets and smartphones.

This training will consist of 10 weekly online live sessions on the weekends (each session is about 3hr and 20min) and 9 optional-to-attend one-hour meetings in between.  We'll use screen-sharing software. Attendees will be able to hear and see the instructors and will communicate with them via a chat room. Between the lessons the student communicate with each other in the online forum.

=== Frameworks, Tools and APIs

Here's the current list of the software that we'll use in this course.

==== Front end

* HTML
* CSS
* Responsive Web Design principles
* JavaScript
* JSON
* http://angularjs.org/[AngularJS framework]
* http://getbootstrap.com/[Twitter Bootstrap framework]
* Google Chrome Web Browser
* WebSockets https://developer.mozilla.org/en-US/docs/WebSockets[on the client]
* http://gruntjs.com/[Grunt] (The JavaScript task runner)
* https://npmjs.org/[NPM]
* http://bower.io/[Bower]
* https://github.com/pivotal/jasmine[Jasmine framework]

==== Middle Tier

* http://www.oracle.com/technetwork/java/javase/overview/index.html/[Java SE 8]
* http://www.oracle.com/technetwork/java/javaee/overview/index.html[Java EE 7]
* SQL: JDBC or http://mybatis.github.io/mybatis-3/[MyBatis]
* https://spring.io/blog/2013/11/01/spring-framework-4-0-rc1-available[Spring 4 Framework] (some modules)
* http://www.wildfly.org/[JBoss Wildfly] Application Server
* WebSockets https://jcp.org/en/jsr/detail?id=356[on the server (JSR-356])
* JMS 2.0
* http://docs.oracle.com/javaee/7/tutorial/doc/jaxrs-advanced.htm#GJJXE[JAX-RS] (Java API for RESTful Web services)
* http://www.gradle.org/[Gradle]  (build automation)
* https://code.google.com/p/spock/[Spock] or JUnit (unit testing and mocking)

==== DBMS

* Oracle

==== Miscellaneous

* Git (version control system), GitHub (Git hosting service)
* IntelliJ IDEA IDE Ultimate. Our special thanks to JetBrains for providing free http://www.jetbrains.com/idea/buy/classroom_license.html[classroom license] for all the students enrolled into this class.

=== FAQ

1. _I'm a professional programmer, but have never actually worked in Java.  I took some classes both in SE and EE, worked though several Java books.  Would it be enough?_
+

We don't know. It depends on your ability to learn new material. If your Java is a little rusty, start watching http://www.youtube.com/user/yfain[Java video lessons by Yakov Fain] - they are being published weekly.

2. _I have Eclipse Juno with Java EE 7.  I'm currently taking Intro to Android Programming and would prefer to keep my existing setup._
+

In this training we use IntelliJ IDEA IDE as it has good support of both JavaScript and Java. All instructions will be provided for this IDE only. Instructors will not be addressing issues related to Eclipse IDE.

3. _What other software do I need to have installed on my laptop?_
+

We're providing instructions for the software required for each lesson as we proceed.  

4. _How deep knowledge of SQL is required? I'm OK with not too complicated queries._
+

No deep knowledge of SQL is required.

5. _Are we starting JavaScript practically from scratch?_
+

Yes, but in a fast pace.

6. _How much "extra help" will be available if I'd be having a trouble with something?_
+

Students communicate with each other by posting questions/answers in the forum. Instructors are monitoring this list too. Also, there is one hour consultation time between the lesson where instructors answer questions.

7. _Do I need to know GIT for this course?_
+

Yes, you do. Please watch http://www.youtube.com/watch?v=MXDRIUGW3X4[this video] to get familiar with GIT and GitHub. 

8. _I'm still not sure if I can absorb all these materials within 10 weeks_
+

This is an intensive training that's targeted busy professionals who need to master new software in a fast pace. If you can't commit 15-20 hours a week for studying, do not enroll as you'll be wasting money.

9. _When's the Next Training_

Currently we're planning to run the next public training starting July 27, 2014. The information about the next public training will be announced at http://www.faratasystems.com. To get on the waiting list please email at training@faratasystems.com.

You can also request this training to be conducted for your organization online. Just email you inquiry to training@faratasystems.com.

=== Instructors

This course is taught by three instructors who are practitioners employed by http://faratasystems.com/[Farata Systems]:

* *Yakov Fain* - Co-founder of Farata Systems, the IT consultancy. https://java.net/website/java-champions/bios.html[Java Champion]. Organizer of the http://www.meetup.com/NJFlex/[Princeton Java Users Group]. Authored and co-authored a number of technical books on programming. Yakov presented on various international conferences on Java and JavaScript related topics.

* *Viktor Gamov* - Lead software developer in Farata Systems. Helps financial companies with various Java and HTML5 projects. Co-organizer of the Princeton Java Users Group. Co-author of the O'Reilly book on http://enterprisewebbook.com/[Enterprise Web Development]. Viktor presented on various international conferences on Java and JavaScript related topics.

* *Anton Moiseev* - Lead software developer in Farata Systems. Specializes in developing e-Commerce applications. Enjoys everything HTML5-related. Authored and taught trainings on developing Web applications with Ext JS framework.

Other professionals from Farata Systems may also be invited to share their experience in developing and deploying complex enterprise systems.
